Add a way to create compile_commands.json, lifted from godot-cpp.
maiself/godot-python-extension pull request #25
Opened 2024-10-24 17:33 UTC by Ivorforce

compile_commands.json can be used for IDE support, for example CLion.

Feel free to move the additions around in your SConstruct. I didn't feel comfortable with any spot in particular so I just placed them somewhere.

2025-02-15 02:06 UTC, maiself requested changes
Minor things, can merge immediately after fixed.

2025-02-15 02:06 UTC, maiself commented on SConstruct
> +env.Tool("compilation_db")
Not sure if the location of this is important. Would like it with the other aliases above, but don't feel confident that nothing would break.

2025-02-15 02:06 UTC, maiself commented on SConstruct
> +opts.Add(
- [ ] Replace space indent with tab indent.
- [ ] Move these two options below the `"single_source"` option below.

2025-02-16 14:29 UTC, Ivorforce commented on SConstruct
> +env.Tool("compilation_db")
It's good that you have an opinion on this, I just placed it anywhere really. I moved it to the aliases above, works fine 👍

2025-02-16 14:29 UTC, Ivorforce commented on SConstruct
> +def validate_parent_dir(key, val, env):
Oh, cannot believe I didn't search for that before adding!

2025-02-16 14:30 UTC, Ivorforce commented on SConstruct
> +opts.Add(
Oh, whoops, totally overrelied on my IDE to do tabs automatically. Both fixed!

2025-02-16 15:46 UTC, merged